DROP TABLE IF EXISTS scoreBoard;
CREATE TABLE scoreBoard(scoreBoardId INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);

DROP TABLE IF EXISTS score;
CREATE TABLE score(scoreId INTEGER PRIMARY KEY AUTOINCREMENT, participantName TEXT);
