DROP TABLE IF EXISTS scoreBoard;
DROP TABLE IF EXISTS score;

CREATE TABLE scoreBoard (
scoreBoardId INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
description TEXT NOT NULL,
uniqueKey TEXT NOT NULL UNIQUE CHECK(LENGTH(uniqueKey) = 8),
settingId INTEGER NOT NULL
);

CREATE TABLE score (
scoreId INTEGER PRIMARY KEY AUTOINCREMENT,
participantName TEXT NOT NULL,
points INTEGER NOT NULL,
scoreBoardId INTEGER,
FOREIGN KEY (scoreBoardId) REFERENCES scoreBoard(scoreBoardId) ON DELETE CASCADE
);